CREATE TABLE users (
  id BINARY(16) PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  surname VARCHAR(150) NOT NULL,
  email VARCHAR(255) UNIQUE,
  passwd VARCHAR(255) NOT NULL,
  department VARCHAR(100) NOT NULL,
  description VARCHAR(255) NOT NULL DEFAULT "",
  rol VARCHAR(255) NOT NULL DEFAULT "user",
  birthdate DATE NOT NULL,
  active TINYINT NOT NULL DEFAULT 1,
  creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE logins (
  id BINARY(16) PRIMARY KEY,
  user_id BINARY(16),
  ip VARCHAR(20) NOT NULL,
  device VARCHAR(255) NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT fk_user_login FOREIGN KEY (user_id) REFERENCES users (id)
);